# Generated by Django 4.0.2 on 2024-06-15 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('actors', models.ManyToManyField(to='db.Actor')),
                ('genres', models.ManyToManyField(to='db.Genre')),
            ],
        ),
    ]
